name: cert-manager-auto-renew
services:
  cert-manager:
    type: Deployment
    namespace: cert-manager
    settings:
      containers:
        - name: cert-manager
          image: quay.io/jetstack/cert-manager-controller:v1.11.0
          args:
            - --v=2
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --leader-elect=true
  cluster-issuer:
    type: CustomResourceDefinition
    namespace: cert-manager
    settings:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: your-email@example.com
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
            - http01:
                ingress:
                  class: nginx
